slstatus &
flameshot &
simplescreenrecorder --start-hidden &
picom &
setxkbmap -layout us,gr -option grp:alt_shift_toggle &
feh --bg-fill ~/Documents/suckless64/other/wallpapers/Minimal\ Mojave-1.jpg &
xset s off -dpms &
pipewire &
pipewire-pulse &
exec dwm
